[package]
name = "awgctl"
version = "0.2.0"
description = "Manage AmneziaWG servers"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
thiserror = "2"
toml = "1"
wireguard-conf = { version = "2", features = ["amneziawg", "serde"] }
sudo2 = "0.2"
serde = { version = "1", features = ["derive"] }
time = { version = "0.3", features = [
  "serde",
  "serde-human-readable",
  "local-offset",
] }
network-interface = "2"
qrcode = { version = "0.14" }
